name: Set up Conda environment

inputs:
  environment-file:
    description: Conda environment file to use.
    default: environment.yml

runs:
  using: composite
  steps:
    - name: Install ${{ inputs.environment-file }}
      uses: mamba-org/setup-micromamba@v2
      with:
        environment-file: ${{ inputs.environment-file }}
        environment-name: test
        condarc-file: ci/.condarc
        cache-environment: true
        cache-downloads: true
        # keep post step simple to avoid JSON parsing problems
        post-cleanup: environment

    - name: Uninstall pyarrow (optional)
      if: ${{ env.REMOVE_PYARROW == '1' }}
      shell: bash -el {0}
      run: |
        micromamba remove -y -n test pyarrow
