name: Set up Conda environment
inputs:
  environment-file:
    description: Conda environment file to use.
    default: environment.yml
  environment-name:
    description: Name to use for the Conda environment
    default: test
  extra-specs:
    description: Extra packages to install
    required: false
runs:
  using: composite
  steps:
    - name: Install ${{ inputs.environment-file }}
      uses: mamba-org/provision-with-micromamba@v15
      with:
        environment-file: ${{ inputs.environment-file }}
        environment-name: ${{ inputs.environment-name }}
        extra-specs: ${{ inputs.extra-specs }}
        channels: conda-forge
        channel-priority: ${{ runner.os == 'macOS' && 'flexible' || 'strict' }}
        condarc-file: ci/condarc.yml
        cache-env: true
        cache-downloads: true
