# File : .pep8speaks.yml

scanner:
    diff_only: True  # If True, errors caused by only the patch are shown

# Opened issue in pep8speaks, so we can directly use the config in setup.cfg
# (and avoid having to duplicate it here):
# https://github.com/OrkoHunter/pep8speaks/issues/95

pycodestyle:
    max-line-length: 79
    ignore:
        - W503,  # line break before binary operator
        - W504,  # line break after binary operator
        - E402,  # module level import not at top of file
        - E722,  # do not use bare except
        - E731,  # do not assign a lambda expression, use a def
        - C406,  # Unnecessary list literal - rewrite as a dict literal.
        - C408,  # Unnecessary dict call - rewrite as a literal.
        - C409   # Unnecessary list passed to tuple() - rewrite as a tuple literal.
