# Cannot define these sections in pyproject.toml yet due to
# https://github.com/prefix-dev/pixi/issues/1801
[workspace]
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64", "osx-64", "osx-arm64", "win-64"]
name = "pandas"

[dependencies]
# Build dependencies
versioneer = ">=0.29"
cython = ">3.1.0,<4.0.0a0"
meson = ">=1.2.3,<2"
meson-python = ">=0.19.0,<1"
c-compiler = "*"
cxx-compiler = "*"
pip = ">=26"

# Required dependencies
python-dateutil = ">=2.8.2"

[feature.numpy.dependencies]
numpy = ">=1.26.0,<3"

[feature.numpy-nightly.pypi-dependencies]
numpy = { version = "*", index = "https://pypi.anaconda.org/scientific-python-nightly-wheels/simple" }

[target.win.dependencies]
tzdata = ">=2023.3"

[feature.py311.dependencies]
python = "3.11.*"

[feature.py312.dependencies]
python = "3.12.*"

[feature.py313.dependencies]
python = "3.13.*"

[feature.py314.dependencies]
python = "3.14.*"

[feature.py313-freethreading.dependencies]
python-freethreading = "3.13.*"

[feature.test-base.dependencies]
pytest = ">=8.3.4"
pytest-xdist = ">=3.6.1"
hypothesis = ">=6.116.0"
pytest-cov = ">=7.0.0"

[feature.test-network.dependencies]
pytest-localserver = ">=0.9.0"
# TODO: Try changing to boto3 >= instead
boto3 = "==1.40.46"

[feature.test-clipboard.dependencies]
pytest-qt = ">=4.4.0"
pyqt = ">=5.15.9"
qtpy = ">=2.4.2"

[feature.pyarrow.dependencies]
pyarrow = ">=13.0.0"

[feature.pyarrow-nightly.pypi-dependencies]
pyarrow = { version = "*", index = "https://pypi.anaconda.org/scientific-python-nightly-wheels/simple" }

[feature.optional-dependencies.dependencies]
adbc-driver-postgresql = ">=1.2.0"
adbc-driver-sqlite = ">=1.2.0"
beautifulsoup4 = ">=4.12.3"
blosc = ">=1.21.3"
bottleneck = ">=1.4.2"
fastparquet = ">=2024.11.0"
fsspec = ">=2024.10.0"
html5lib = ">=1.1"
gcsfs = ">=2024.10.0"
jinja2 = ">=3.1.5"
lxml = ">=5.3.0"
matplotlib = ">=3.9.3"
numba = ">=0.60.0"
numexpr = ">=2.10.2"
odfpy = ">=1.4.1"
openpyxl = ">=3.1.5"
psycopg2 = ">=2.9.10"
pyiceberg = ">=0.8.1"
pymysql = ">=1.1.1"
pyreadstat = ">=1.2.8"
pytables = ">=3.10.1"
python-calamine = ">=0.3.0"
pytz = ">=2020.1"
pyxlsb = ">=1.0.10"
s3fs = ">=2024.10.0"
scipy = ">=1.14.1"
sqlalchemy = ">=2.0.36"
tabulate = ">=0.9.0"
xarray = ">=2024.10.0"
xlrd = ">=2.0.1"
xlsxwriter = ">=3.2.0"
zstandard = ">=0.23.0"

[feature.minimum-versions]
solve-strategy = "lowest-direct"

[feature.downstream.dependencies]
cftime = "*"
dask = "*"
seaborn = "*"
scikit-learn = "*"
statsmodels = "*"
pandas-datareader = "*"
pyyaml = "*"
xarray = ">=2024.10.0"

[feature.benchmarks.dependencies]
asv = ">=0.6.5"
py-rattler = "*"  # for environment_type in asv.conf.json

[feature.documentation.dependencies]
gitpython = "*" # obtain contributors from git for whatsnew
ipykernel = "*" # used in doc/source/user_guide/style.ipynb
ipywidgets = "*" # used in doc/source/user_guide/style.ipynb
nbconvert = ">=7.11.0"
nbformat = "*" # used in doc/source/user_guide/style.ipynb
nbsphinx = "*"
numpydoc = "*"
pandoc = "*"
seaborn = "*" # used in doc/source/user_guide/style.ipynb
sphinx = "*"
sphinx-design = "*"
sphinx-copybutton = "*"

[feature.documentation.pypi-dependencies]
# temporary installed with pip with custom patch until released
# https://github.com/pydata/pydata-sphinx-theme/issues/2176
pydata-sphinx-theme = {url = "https://github.com/jorisvandenbossche/pydata-sphinx-theme/archive/refs/heads/v0.16.1+dismissable-announcement-banner.zip"}

[feature.website.dependencies]
feedparser = "*"
jinja2 = "*"
jupyterlite-core = "*"
jupyterlite-pyodide-kernel = "*"
markdown = "*"
packaging = "*"
pygments = "*" # Code highlighting
pytest = "*"
pyyaml = "*"
requests = "*"

[environments]
py311 = { features = ["py311", "numpy", "test-base", "test-clipboard", "test-network", "pyarrow", "optional-dependencies"] }
py312 = { features = ["py312", "numpy", "test-base", "test-clipboard", "test-network", "pyarrow", "optional-dependencies"] }
py313 = { features = ["py313", "numpy", "test-base", "test-clipboard", "test-network", "pyarrow", "optional-dependencies"] }
py314 = { features = ["py314", "numpy", "test-base", "test-clipboard", "test-network", "pyarrow", "optional-dependencies"] }
no-pyarrow = { features = ["py313", "numpy", "test-base", "test-clipboard", "test-network", "optional-dependencies"] }
minimum-versions = { features = ["py311", "numpy", "test-base", "test-clipboard", "test-network", "pyarrow", "optional-dependencies", "minimum-versions"] }
py313-freethreading = { features = ["py313-freethreading", "numpy", "test-base"] }
numpy-nightly = { features = ["py313", "numpy-nightly", "test-base"] }
pyarrow-nightly = { features = ["py313", "numpy", "test-base", "pyarrow-nightly"] }
downstream = { features = ["py313", "numpy", "test-base", "downstream"] }
asv = { features = ["py313", "numpy", "pyarrow", "optional-dependencies", "benchmarks" ]}
docs-and-web = { features = ["py312", "numpy", "pyarrow", "optional-dependencies", "documentation", "website" ]}


[tasks]
[tasks.uninstall-pandas]
cmd = "python -m pip uninstall -y pandas || true"

[tasks.build-pandas]
args = [
  { "arg" = "editable", "default" = "" },
  { "arg" = "werror", "default" = "" },
]
# https://github.com/pandas-dev/pandas/pull/65228, changed with Meson 1.11
env = { PKG_CONFIG_PATH = "$CONDA_PREFIX/lib/pkgconfig" }
cmd = "python -m pip install --verbose {{ editable }} . --no-build-isolation --no-deps --config-settings builddir=build/$PIXI_ENVIRONMENT_NAME {{ werror }}"
depends-on = ["uninstall-pandas"]

[tasks.ci-test-pandas]
args = [
  { "arg" = "pytest_flags" },
  { "arg" = "numprocesses", "default" = "auto" },
  { "arg" = "pytest_target", "default" = "pandas" },
]
cmd = [
  "python",
  "-m",
  "pytest",
  "-r",
  "fE",
  "{{ pytest_flags }}",
  "--numprocesses={{ numprocesses }}",
  "--dist=worksteal",
  "--capture=no",
  "--cov=pandas",
  "--cov-report=xml",
  "--cov-append",
  "{{ pytest_target }}",
]

[tasks.ci-asv]
cmd = [
  "cd",
  "asv_bench",
  "&&",
  "python",
  "-m",
  "asv",
  "machine",
  "--yes",
  "&&",
  "python",
  "-W",
  "error",
  "-m",
  "asv",
  "run",
  "--quick",
  "--dry-run",
  "--durations=30",
  "--python=same",
  "--show-stderr",
]

[tasks.ci-test-single-page-doc]
args = [
  { "arg" = "page_to_build" }
]
cmd = [
  "python",
  "doc/make.py",
  "--warnings-are-errors",
  "--no-browser",
  "--single",
  "{{ page_to_build }}",
  "&&",
  "python",
  "doc/make.py",
  "clean",
]

[tasks.ci-test-nbconvert-doc-notebooks]
args = [
  { "arg" = "notebooks" }
]
cmd = [
  "python",
  "-m",
  "jupyter",
  "nbconvert",
  "--execute",
  "{{ notebooks }}",
  "--to",
  "notebook",
  "--stdout",
  ">/dev/null",
]

[tasks.ci-build-documentation]
args = [
  { "arg" = "doc_type", "choices" = ["html", "zip_html"] }
]
cmd = [
  "python",
  "doc/make.py",
  "--warnings-are-errors",
  "{{ doc_type }}",
]

[tasks.ci-test-website]
cmd = [
  "python",
  "-m",
  "pytest",
  "web",
]

[tasks.ci-build-website]
cmd = [
  "python",
  "web/pandas_web.py",
  "web/pandas",
  "--target-path=web/build",
]

[tasks.ci-build-interactive_terminal]
cmd = [
  "python",
  "-m",
  "jupyter",
  "lite",
  "build",
]
