FROM python:3.10.8-alpine

RUN apk update & apk upgrade
RUN apk add gcc g++ libc-dev

COPY requirements-minimal.txt /tmp
RUN python -m pip install -r /tmp/requirements-minimal.txt

WORKDIR /home/pandas
CMD ["/bin/sh"]
