FROM python:3.10.8

RUN apt update && apt upgrade -y

RUN python -m pip install \
  cython \
  hypothesis \
  numpy \
  pytest \
  pytest-asyncio \  
  pytz \
  python-dateutil \
  versioneer

WORKDIR /home/pandas
CMD ["/bin/bash"]
