FROM python:3.10.8-slim

RUN apt update && apt upgrade -y
RUN apt install -y gcc g++

COPY requirements-minimal.txt /tmp
RUN python -m pip install -r /tmp/requirements-minimal.txt

WORKDIR /home/pandas
CMD ["/bin/bash"]
