FROM quay.io/condaforge/mambaforge

RUN apt update && apt upgrade -y
RUN DEBIAN_FRONTEND=noninteractive apt install -y tzdata

RUN mamba env create -f \
  https://raw.githubusercontent.com/pandas-dev/pandas/main/environment.yml

WORKDIR /home/pandas
CMD ["/bin/sh"]
