# This file is generated by /tmp/easy_install-kn_oavq3/numpy-1.9.0/setup.py
# It contains system_info results at the time of building this package.
__all__ = ["get_info","show"]

atlas_blas_info={}
lapack_info={}
openblas_info={}
lapack_src_info={}
atlas_blas_threads_info={}
blas_src_info={}
lapack_mkl_info={}
blas_info={}
atlas_threads_info={}
mkl_info={}
atlas_info={}
openblas_lapack_info={}
blas_opt_info={}
blas_mkl_info={}
lapack_opt_info={}

def get_info(name):
    g = globals()
    return g.get(name, g.get(name + "_info", {}))

def show():
    for name,info_dict in globals().items():
        if name[0] == "_" or type(info_dict) is not type({}): continue
        print(name + ":")
        if not info_dict:
            print("  NOT AVAILABLE")
        for k,v in info_dict.items():
            v = str(v)
            if k == "sources" and len(v) > 200:
                v = v[:60] + " ...\n... " + v[-60:]
            print("    %s = %s" % (k,v))
    