parameters:
  name: ''
  vmImage: ''

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    maxParallel: 11
    matrix:
      py27_np_19:
        ENV_FILE: ci/azure-27-compat.yaml
        CONDA_PY: "27"
        CONDA_ENV: pandas
        TEST_ARGS: "--skip-slow --skip-network"

      py36_locale:
        ENV_FILE: ci/azure-37-locale.yaml
        CONDA_PY: "37"
        CONDA_ENV: pandas
        TEST_ARGS: "--skip-slow --skip-network"
        LOCALE_OVERRIDE: "zh_CN.UTF-8"

      py36_locale_slow:
        ENV_FILE: ci/azure-36-locale_slow.yaml
        CONDA_PY: "36"
        CONDA_ENV: pandas
        TEST_ARGS: "--only-slow --skip-network"

  steps:
    - script: |
        if [ "$(uname)" == "Linux" ]; then sudo apt-get install -y libc6-dev-i386; fi
        echo "Installing Miniconda"{
        ci/incremental/install_miniconda.sh
        export PATH=$HOME/miniconda3/bin:$PATH
        echo "Setting up Conda environment"
        ci/incremental/setup_conda_environment.sh
      displayName: 'Before Install'
    - script: |
        export PATH=$HOME/miniconda3/bin:$PATH
        ci/incremental/build.sh
      displayName: 'Build'
    - script: |
        export PATH=$HOME/miniconda3/bin:$PATH
        ci/script_single.sh
        ci/script_multi.sh
        echo "[Test done]"
      displayName: 'Test'
    - script: |
        export PATH=$HOME/miniconda3/bin:$PATH
        source activate pandas && pushd /tmp && python -c "import pandas; pandas.show_versions();" && popd
    - task: PublishTestResults@2
      inputs:
        testResultsFiles: 'test-data-*.xml'
        testRunTitle: 'Linux'