name: Set up Conda environment with Pixi
description: Create a Conda environment based on the environments section in pixi.toml
inputs:
  environment:
    description: Pixi environment name in pyproject.toml to use.
    required: true
runs:
  using: composite
  steps:
    - name: Install ${{ inputs.environment }}
      uses: prefix-dev/setup-pixi@a09b6247153796b190642a2b53fac4241043cf6f # v0.10.0
      with:
        pixi-version: v0.69.0
        log-level: vv
        manifest-path: pixi.toml
        environments: ${{ inputs.environment }}
        cache: true
        cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
