# flake8: noqa

class Packer:
    def __cinit__(self): ...
    def __init__(
        self,
        default=...,
        encoding=...,
        unicode_errors=...,
        use_single_float=...,
        autoreset: int = ...,
        use_bin_type: int = ...,
    ): ...
    def __dealloc__(self): ...
    def _pack(self, o, nest_limit: int = ...) -> int: ...
    def pack(self, obj): ...
    def pack_ext_type(self, typecode, data): ...
    def pack_array_header(self, size): ...
    def pack_map_header(self, size): ...
    def pack_map_pairs(self, pairs): ...
    def reset(self) -> None: ...
    def bytes(self): ...
