name: Build pandas
description: Rebuilds the C extensions and installs pandas
runs:
  using: composite
  steps:

    - name: Environment Detail
      run: |
        conda info
        conda list
        # Make sure we have the correct environment activated
        conda info | grep -Ei 'environment.+:' | grep -qEiv 'environment.+:.+none'
      shell: bash -el {0}

    - name: Build Pandas
      run: |
        python setup.py build_ext -j $N_JOBS
        python -m pip install -e . --no-build-isolation --no-use-pep517 --no-index
      shell: bash -el {0}
      env:
        # Cannot use parallel compilation on Windows, see https://github.com/pandas-dev/pandas/issues/30873
        N_JOBS: ${{ runner.os == 'Windows' && 1 || 2 }}

    - name: Show dependency versions
      run: python -c "import pandas; pandas.show_versions()"
      shell: bash -el {0}
