name: Build pandas
description: Rebuilds the C extensions and installs pandas
inputs:
  editable:
    description: Whether to build pandas in editable mode (default true)
    default: true
runs:
  using: composite
  steps:

    - name: Environment Detail
      run: |
        micromamba info
        micromamba list
        pip list --pre
      shell: bash -el {0}

    - name: Uninstall existing Pandas installation
      run: |
        if pip show pandas 1>/dev/null; then
          pip uninstall -y pandas
        fi
      shell: bash -el {0}

    - name: Uninstall nomkl
      run: |
        if conda list nomkl | grep nomkl 1>/dev/null; then
          conda remove nomkl -y
        fi
      shell: bash -el {0}

    - name: Build Pandas
      run: |
        if [[ ${{ inputs.editable }} == "true" ]]; then
          pip install -e . --no-build-isolation -v --no-deps \
            --config-settings=setup-args="--werror"
        else
          pip install . --no-build-isolation -v --no-deps \
            --config-settings=setup-args="--werror"
        fi
      shell: bash -el {0}
