name: Build pandas
description: Rebuilds the C extensions and installs pandas
inputs:
  editable:
    description: Whether to build pandas in editable mode (default true)
    default: true
runs:
  using: composite
  steps:

    - name: Environment Detail
      run: |
        micromamba info
        micromamba list
        pip list --pre
      shell: bash -el {0}

    - name: Uninstall existing Pandas installation
      run: |
        if pip show pandas 1>/dev/null; then
          pip uninstall -y pandas
        fi
      shell: bash -el {0}

    - name: Build Pandas
      # wno-error reason: https://github.com/cython/cython/issues/6870
      run: |
        if [[ ${{ inputs.editable }} == "true" ]]; then
          EDITABLE="-e"
        else
          EDITABLE=""
        fi
        pip install $EDITABLE . --no-build-isolation -v --no-deps -Csetup-args="-Werror" -Csetup-args="-Wno-error=unused-parameter"
      shell: bash -el {0}
