from typing import overload

import numpy as np
from numpy import typing as npt

class NAType:
    def __new__(cls, *args, **kwargs): ...

NA: NAType

def is_matching_na(
    left: object, right: object, nan_matches_none: bool = ...
) -> bool: ...
def isposinf_scalar(val: object) -> bool: ...
def isneginf_scalar(val: object) -> bool: ...
def checknull(val: object) -> bool: ...
@overload
def isnaobj(arr: np.ndarray, check_for_any_na=...) -> npt.NDArray[np.bool_]: ...
@overload
def isnaobj(
    arr: np.ndarray, check_for_any_na=True
) -> tuple[npt.NDArray[np.bool_], bool]: ...
def is_numeric_na(values: np.ndarray) -> npt.NDArray[np.bool_]: ...
