import numpy as np

from pandas.io.sas.sas7bdat import SAS7BDATReader

class Parser:
    def __init__(self, parser: SAS7BDATReader) -> None: ...
    def read(self, nrows: int) -> None: ...
    def string_values(self) -> list[np.ndarray]: ...

def collect_page_subheaders(parser: SAS7BDATReader) -> int: ...
