name: Run tests and report results
description: Run pytest and upload the results to Codecov
inputs:
  environment:
    description: Virtual environment in pixi.toml to run tests.
    required: true
  numprocesses:
    description: pytest-xdist numprocesses value
    required: true
  pytest_marker_expression:
    description: pytest marker expression to pass to -m.
    required: true
  pytest_target:
    description: File or directory path to run tests
    required: true
  pandas_future_infer_string:
    description: Environment variable for infer string behavior
    default: '1'
  pandas_future_python_scalars:
    description: Environment variable for Python scalar behavior
    default: '0'
runs:
  using: composite
  steps:
    - name: Test
      env:
        PANDAS_CI: 1
        PANDAS_FUTURE_INFER_STRING: ${{ inputs.pandas_future_infer_string }}
        PANDAS_FUTURE_PYTHON_SCALARS: ${{ inputs.pandas_future_python_scalars }}
        MESONPY_EDITABLE_VERBOSE: 1
        PYTHONDEVMODE: 1
        PYTHONWARNDEFAULTENCODING: 1
        # Clipboard tests
        QT_QPA_PLATFORM: offscreen
      run: |
        pixi run \
          --environment ${{ inputs.environment }} \
          ci-test-pandas \
          '-m ${{ inputs.pytest_marker_expression }}' \
          ${{ inputs.numprocesses }} \
          ${{ inputs.pytest_target }}
      shell: bash -euox pipefail {0}

    - name: Publish test results
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
      with:
        name: Test results
        path: test-data.xml
      if: failure()

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5
      with:
        flags: unittests
        name: codecov-pandas
        fail_ci_if_error: false
      if: failure()
