package:
    name: pandas
    version: {{ environ.get('GIT_DESCRIBE_TAG','').replace('v', '', 1) }}

build:
    number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
    {% if GIT_DESCRIBE_NUMBER|int == 0 %}string: np{{ CONDA_NPY }}py{{ CONDA_PY }}_0
    {% else %}string: np{{ CONDA_NPY }}py{{ CONDA_PY }}_{{ GIT_BUILD_STR }}{% endif %}

source:
    git_url: ../

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - numpy
    - setuptools >=38.6.0
    - python-dateutil >=2.7.3
    - pytz
  run:
    - python {{ python }}
    - {{ pin_compatible('numpy') }}
    - python-dateutil >=2.7.3
    - pytz

test:
  requires:
    - pytest
  commands:
    - python -c "import pandas; pandas.test()"


about:
  home: https://pandas.pydata.org
  license: BSD
