name: Clean closed branch caches
on:
  schedule:
    # 4:10 UTC daily
    - cron: "10 4 * * *"
  pull_request:
    types:
      - closed

permissions: {}

defaults:
  run:
    shell: bash -euxo pipefail {0}

jobs:
  cleanup:
    runs-on: ubuntu-24.04
    if: github.repository_owner == 'pandas-dev'
    steps:
      - name: Clean closed pull request caches
        if: github.event_name == 'pull_request'
        env:
          GH_TOKEN: ${{ github.token }}
        run: >
          gh cache delete
          --repo pandas-dev/pandas
          --all
          --ref refs/pull/${{ github.event.pull_request.number }}/merge
          --succeed-on-no-caches
      - name: Clean all caches
        if: github.event_name == 'schedule'
        env:
          GH_TOKEN: ${{ github.token }}
        run: >
          gh cache delete
          --repo pandas-dev/pandas
          --all
          --succeed-on-no-caches
